# -*- coding: utf-8 -*-
# this file is generated by gen_kdata_schema function, dont't change it
from sqlalchemy.ext.declarative import declarative_base

from zvt.api.data_type import Region, Provider, EntityType
from zvt.domain.quotes import IndexKdataCommon
from zvt.contract.register import register_schema


KdataBase = declarative_base()


class Index1wkKdata(KdataBase, IndexKdataCommon):
    __tablename__ = 'index_1wk_kdata'


register_schema(regions=[Region.CHN, Region.US],
                providers={Region.CHN: [Provider.JoinQuant, Provider.Sina],
                           Region.US: [Provider.Default]},
                db_name='index_1wk_kdata',
                schema_base=KdataBase,
                entity_type=EntityType.Index)


# the __all__ is generated
__all__ = ['Index1wkKdata']
