# -*- coding: utf-8 -*-
# this file is generated by gen_kdata_schema function, dont't change it
from sqlalchemy.ext.declarative import declarative_base

from findy.database.schema.datatype import StockKdataCommon

ofmKdataBase = declarative_base()


class Stock15mKdata(ofmKdataBase, StockKdataCommon):
    __tablename__ = 'stock_15m_kdata'


class Stock15mHfqKdata(ofmKdataBase, StockKdataCommon):
    __tablename__ = 'stock_15m_hfq_kdata'


class Stock15mBfqKdata(ofmKdataBase, StockKdataCommon):
    __tablename__ = 'stock_15m_bfq_kdata'
