# -*- coding: utf-8 -*-
# this file is generated by gen_kdata_schema function, dont't change it
from sqlalchemy.ext.declarative import declarative_base

from findy.database.schema.datatype import StockKdataCommon

hKdataBase = declarative_base()


class Stock1hKdata(hKdataBase, StockKdataCommon):
    __tablename__ = 'stock_1h_kdata'


class Stock1hHfqKdata(hKdataBase, StockKdataCommon):
    __tablename__ = 'stock_1h_hfq_kdata'


class Stock1hBfqKdata(hKdataBase, StockKdataCommon):
    __tablename__ = 'stock_1h_bfq_kdata'
