# -*- coding: utf-8 -*-
# this file is generated by gen_kdata_schema function, dont't change it
from sqlalchemy.ext.declarative import declarative_base

from findy.database.schema.datatype import StockKdataCommon

monKdataBase = declarative_base()


class Stock1monKdata(monKdataBase, StockKdataCommon):
    __tablename__ = 'stock_1mon_kdata'


class Stock1monHfqKdata(monKdataBase, StockKdataCommon):
    __tablename__ = 'stock_1mon_hfq_kdata'


class Stock1monBfqKdata(monKdataBase, StockKdataCommon):
    __tablename__ = 'stock_1mon_bfq_kdata'
