# -*- coding: utf-8 -*-
# this file is generated by gen_kdata_schema function, dont't change it
from sqlalchemy.ext.declarative import declarative_base

from findy.database.schema.datatype import StockKdataCommon

fhKdataBase = declarative_base()


class Stock4hKdata(fhKdataBase, StockKdataCommon):
    __tablename__ = 'stock_4h_kdata'


class Stock4hHfqKdata(fhKdataBase, StockKdataCommon):
    __tablename__ = 'stock_4h_hfq_kdata'


class Stock4hBfqKdata(fhKdataBase, StockKdataCommon):
    __tablename__ = 'stock_4h_bfq_kdata'
