# -*- coding: utf-8 -*-
# this file is generated by gen_kdata_schema function, dont't change it
from sqlalchemy.ext.declarative import declarative_base

from zvt.api.data_type import Region, Provider, EntityType
from zvt.domain.quotes import BlockKdataCommon
from zvt.contract.register import register_schema

KdataBase = declarative_base()


class Block1wkKdata(KdataBase, BlockKdataCommon):
    __tablename__ = 'block_1wk_kdata'


register_schema(regions=[Region.CHN, Region.US],
                providers={Region.CHN: [Provider.EastMoney],
                           Region.US: [Provider.Default]},
                db_name='block_1wk_kdata',
                schema_base=KdataBase,
                entity_type=EntityType.Block)


# the __all__ is generated
__all__ = ['Block1wkKdata']
