# -*- coding: utf-8 -*-
# this file is generated by gen_kdata_schema function, dont't change it
from sqlalchemy.ext.declarative import declarative_base

from zvt.api.data_type import Region, Provider, EntityType
from zvt.domain.quotes import EtfKdataCommon
from zvt.contract.register import register_schema

KdataBase = declarative_base()


class Etf1dKdata(KdataBase, EtfKdataCommon):
    __tablename__ = 'etf_1d_kdata'


register_schema(regions=[Region.CHN, Region.US],
                providers={Region.CHN: [Provider.Sina],
                           Region.US: [Provider.Default]},
                db_name='etf_1d_kdata',
                schema_base=KdataBase,
                entity_type=EntityType.ETF)


# the __all__ is generated
__all__ = ['Etf1dKdata']
