# -*- coding: utf-8 -*-
# this file is generated by gen_kdata_schema function, dont't change it
from sqlalchemy.ext.declarative import declarative_base

from zvt.api.data_type import Region, Provider, EntityType
from zvt.domain.quotes import StockKdataCommon
from zvt.contract.register import register_schema

KdataBase = declarative_base()


class Stock4hKdata(KdataBase, StockKdataCommon):
    __tablename__ = 'stock_4h_kdata'


class Stock4hHfqKdata(KdataBase, StockKdataCommon):
    __tablename__ = 'stock_4h_hfq_kdata'


class Stock4hBfqKdata(KdataBase, StockKdataCommon):
    __tablename__ = 'stock_4h_bfq_kdata'


register_schema(regions=[Region.CHN, Region.US],
                providers={Region.CHN: [Provider.JoinQuant, Provider.BaoStock],
                           Region.US: [Provider.Yahoo]},
                db_name='stock_4h_kdata',
                schema_base=KdataBase,
                entity_type=EntityType.Stock)

register_schema(regions=[Region.CHN, Region.US],
                providers={Region.CHN: [Provider.JoinQuant, Provider.BaoStock],
                           Region.US: [Provider.Yahoo]},
                db_name='stock_4h_hfq_kdata',
                schema_base=KdataBase,
                entity_type=EntityType.Stock)

register_schema(regions=[Region.CHN, Region.US],
                providers={Region.CHN: [Provider.JoinQuant, Provider.BaoStock],
                           Region.US: [Provider.Yahoo]},
                db_name='stock_4h_bfq_kdata',
                schema_base=KdataBase,
                entity_type=EntityType.Stock)


# the __all__ is generated
__all__ = ['Stock4hKdata', 'Stock4hHfqKdata', 'Stock4hBfqKdata']
